api_platform:
    title: 'Symfony Shop API'
    description: 'API for Symfony Shop'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header